# Reactor mechanism
mechanism: 'PolyMech.yaml'

# Simulation parameters
time_total: 5 # Total residence time [s]
temperature_C: 1000.0  # Operating temperature [Celsius]
pressure: 101325.0  # Operating pressure [Pascal] (one atmosphere)

# Initial composition (mole fractions)
initial_composition:
  CH4: 0.9
  C2H6: 0.04
  C3H8: 0.04
  CO2: 0.02

# Recycle configuration
recycle_ratios:
  CH4: 1.0
  C2H6: 1.0
  C3H8: 1.0


sigma: 1.0e-7  # Concentration threshold (mol/m³)
max_iterations: 20  # Maximum number of recycle iterations
convergence_tol: 1.0e-6  # Convergence tolerance for recycle loop